// Mangaka pages — barrel export
export { MangakaDashboardPage } from './MangakaDashboardPage';
export { SeriesListPage } from './SeriesListPage';
export { CreateSeriesPage } from './CreateSeriesPage';
export { ManuscriptsPage } from './ManuscriptsPage';
export { MangakaTasksPage } from './MangakaTasksPage';
export { MangakaWalletPage } from './MangakaWalletPage';
export { MangakaSettingsPage } from './MangakaSettingsPage';
export { ChapterDetailPage } from './ChapterDetailPage';
export { SeriesDetailPage } from './SeriesDetailPage';
