// Global TypeScript Types — schema DTOs + status unions

export type { UserRole, User } from '../stores/authStore';

export type {
  ApiResponse,
  PagedResult,
  PagedApiResponse,
  SeriesDto,
  ChapterDto,
  PageDto,
  RegionDto,
  TasksDto,
  TaskVersionDto,
  WalletDto,
  WalletDetailsDto,
  TransactionDto,
  NotificationDto,
  ContractDto,
  ApprovedSeriesContractDto,
  ContractAddendumDto,
  UserResponseDto,
  AuthResponseDto,
  AssistantResponseDto,
  RegisterResponseDto,
  ReconciliationReportDto,
  CreateSeriesDto,
  CreateTaskDto,
  CreateContractDto,
  CreateRegionDto,
  SubmitTaskDto,
  ResolveDisputeDto,
  VoteSeriesRequestDto,
  DepositRequestDto,
  WithdrawRequestDto,
  RegisterDto,
  LoginDto,
  RefreshTokenDto,
  PlatformWalletDto,
  TopUpPlatformWalletDto,
  PortfolioSampleDto,
  SeriesAssistantDto,
} from '../api/generated/types';

export type {
  SeriesStatus,
  ChapterStatus,
  PageStatus,
  TaskStatus,
  TransactionType,
  AnnotationType,
  DisputeResolution,
  VoteType,
  UserAccountStatus,
} from './status.types';
